feat: add markdown glamour styles
overmindtech/cli pull request #245
Opened 2024-04-12 12:36 UTC by getinnocuous

This is fairly standalone and can be merged into main once #237 has.

2024-04-12 12:46 UTC, DavidS-ovm approved these changes

2024-04-12 12:59 UTC, getinnocuous commented
![dark-theme](https://github.com/overmindtech/cli/assets/9265979/2ac0f19b-ce78-48ab-a5cb-7414162f0e4d)
![light-theme](https://github.com/overmindtech/cli/assets/9265979/3c683745-711e-40a7-91c1-21eb5407c7e2)

2024-04-12 13:07 UTC, DavidS-ovm requested changes
Using `markdownToString` fails with a segfault. adding the missing error handling reveals

```
open ./overmind-theme.json: no such file or directory
```

This should instead use `embed`, e.g. like https://github.com/overmindtech/cli/blob/12b9c379d62382e7b2848916acb3d1b574ad5e4e/cmd/root.go#L32-L33

2024-04-12 13:07 UTC, DavidS-ovm commented on cmd/theme.go
>  	r, _ := glamour.NewTermRenderer(
Here and below is missing error handling.

2024-04-12 13:22 UTC, DavidS-ovm commented
@getinnocuous maybe add a small test for the method so I don't have to run the code in my head?

2024-04-15 07:33 UTC, DavidS-ovm commented
I've added the test to give you a leg up here, @getinnocuous .

Before merging this also should be rebased and squashed to clean up the history.

2024-04-16 13:53 UTC, DavidS-ovm approved these changes
Sweet! Please don't forget to rebase or squash this before (or during) merge.

2024-04-16 13:56 UTC, merged